# Generated by Django 5.0.3 on 2025-04-08 06:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_product_slug_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mobile',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
