# Generated by Django 5.0.3 on 2025-07-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_customer_address_customer_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
